### ISSUE TITLE
Improve stability of PR jobs

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/nativescript-cli-tests#200]
Currently ~10% of the jobs are failing with 
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/nsbuilduser/workspace/CLI-pr-tests-smoke-osx/tests/build/android/build_android_tests.py", line 99, in test_001_build_android
    assert (after_build - before_build).total_seconds() < 20, "Incremental build takes more then 20 sec."
AssertionError: Incremental build takes more then 20 sec.
```
Another 10% are failing because of other reasons, so we have ~80% successes in PR jobs.

Let's spend some effort to make success rate of PR at least 95%.

**Comment by dtopuzov** [comment]
Improved
